#!/bin/sh

PORTSDIR=/usr/ports
MAINTAINER=ruby@freebsd.org

LINES=$(  fetch -q -o- "https://portscout.freebsd.org/rss/rss.cgi?m=${MAINTAINER}" | \
		xml sel -t -m "//rss/channel/item" -v "port:portcat" -o '/' -v "port:portname" -o ',' -v 'port:version' -o ',' -v 'port:newversion' -n | \
		sort
      )

for LINE in ${LINES} ; do
  PORT=$(echo ${LINE} | cut -d, -f 1)

  OLDMAJOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 1)
  NEWMAJOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 1)
  OLDMINOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 2)
  NEWMINOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 2)
  OLDMICRO=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 3)
  NEWMICRO=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 3)

  if [ "${OLDMAJOR}" = "" ]; then OLDMAJOR=0 ; fi
  if [ "${NEWMAJOR}" = "" ]; then NEWMAJOR=0 ; fi
  if [ "${OLDMINOR}" = "" ]; then OLDMINOR=0 ; fi
  if [ "${NEWMINOR}" = "" ]; then NEWMINOR=0 ; fi
  if [ "${OLDMICRO}" = "" ]; then OLDMICRO=0 ; fi
  if [ "${NEWMICRO}" = "" ]; then NEWMICRO=0 ; fi

  if [ ${OLDMAJOR} = ${NEWMAJOR} -a ${OLDMINOR} = ${NEWMINOR} -a ${OLDMICRO} = ${NEWMICRO} ]; then
    if [ $(make -C ${PORTSDIR}/${PORT} -V DEPRECATED | wc -c | xargs) -le 1 ]; then
      # not deprecated, print it
      echo ${LINE}
    fi
  fi

done

for LINE in ${LINES} ; do
  PORT=$(echo ${LINE} | cut -d, -f 1)

  OLDMAJOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 1)
  NEWMAJOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 1)
  OLDMINOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 2)
  NEWMINOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 2)

  if [ "${OLDMAJOR}" = "" ]; then OLDMAJOR=0 ; fi
  if [ "${NEWMAJOR}" = "" ]; then NEWMAJOR=0 ; fi
  if [ "${OLDMINOR}" = "" ]; then OLDMINOR=0 ; fi
  if [ "${NEWMINOR}" = "" ]; then NEWMINOR=0 ; fi

  if [ ${OLDMAJOR} = ${NEWMAJOR} -a ${OLDMINOR} = ${NEWMINOR} ]; then
    if [ ${OLDMICRO} != ${NEWMICRO} ]; then
      if [ $(make -C ${PORTSDIR}/${PORT} -V DEPRECATED | wc -c | xargs) -le 1 ]; then
        # not deprecated, print it
        echo ${LINE}
      fi
    fi
  fi

done

for LINE in ${LINES} ; do
  PORT=$(echo ${LINE} | cut -d, -f 1)

  OLDMAJOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 1)
  NEWMAJOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 1)

  if [ "${OLDMAJOR}" = "" ]; then OLDMAJOR=0 ; fi
  if [ "${NEWMAJOR}" = "" ]; then NEWMAJOR=0 ; fi

  if [ ${OLDMAJOR} = ${NEWMAJOR} ]; then
    if [ ${OLDMINOR} != ${NEWMINOR} ]; then
      if [ $(make -C ${PORTSDIR}/${PORT} -V DEPRECATED | wc -c | xargs) -le 1 ]; then
        # not deprecated, print it
        echo ${LINE}
      fi
    fi
  fi

done

for LINE in ${LINES} ; do
  PORT=$(echo ${LINE} | cut -d, -f 1)

  OLDMAJOR=$(echo ${LINE} | cut -d, -f 2 | cut -d\. -f 1)
  NEWMAJOR=$(echo ${LINE} | cut -d, -f 3 | cut -d\. -f 1)

  if [ "${OLDMAJOR}" = "" ]; then OLDMAJOR=0 ; fi
  if [ "${NEWMAJOR}" = "" ]; then NEWMAJOR=0 ; fi

  if [ ${OLDMAJOR} != ${NEWMAJOR} ]; then
    if [ $(make -C ${PORTSDIR}/${PORT} -V DEPRECATED | wc -c | xargs) -le 1 ]; then
      # not deprecated, print it
      echo ${LINE}
    fi
  fi

done
